plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lotus.nianfo'
    compileSdk 34

    defaultConfig {
        applicationId "com.lotus.nianfo"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("D:/nianfo_keystore/nianfo-release-key.jks")
            storePassword "nianfo123456"
            keyAlias "nianfo"
            keyPassword "nianfo123456"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "九品莲台.apk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.9.0'
}
